GET http://localhost:3000/spec

###
GET http://localhost:3000/spec/656c425f5b17c7de57feb28a


###

POST http://localhost:3000/spec
Content-Type: application/json

{
    "title": "new spec",
    "content": "cdvvntjrnbtrkb kgmkrtbvtrm",
    "status": "In progress",
    "date": "2023-11-27",
    "participants": ["A", "S"]
}
###

DELETE http://localhost:3000/spec/656d9d9979469e18e700b164


###

PATCH http://localhost:3000/656d9d9979469e18e700b164
Content-Type: application/json

{
    "order": "3"
}

###

POST http://localhost:3000/kpi
Content-Type: application/json

{
    "mission": "mission",
    "option": "with in",   
    "deta": 3
}

###
GET http://localhost:3000/kpi/
