GET http://localhost:3000/spec

###
GET http://localhost:3000/spec/657ef62a8f3f24d27dfcd13e


###

POST http://localhost:3000/spec
Content-Type: application/json

{
    "title": "new spec",
    "content": "cdvvntjrnbtrkb kgmkrtbvtrm",
    "status": "In progress",
    "date": "2023-11-27",
    "participants": ["A", "S"]
}
###

DELETE http://localhost:3000/spec/657ef62a8f3f24d27dfcd13e


###

PATCH http://localhost:3000/656d9d9979469e18e700b164
Content-Type: application/json

{
    "order": "3"
}

###

POST http://localhost:3000/kpi
Content-Type: application/json

{
    "mission": "mission",
    "option": "with in",   
    "date": 3
}

###

DELETE http://localhost:3000/kpi/65705174dc8928fb43ef9c9a

###
GET http://localhost:3000/kpi/

###

GET http://localhost:3000/spec/656dc9c55909cbcc700a6d75/kpi

###

#// insert spec in kpi
POST http://localhost:3000/specs/657046964a30eedcff3bd72e/kpi/6570462f4a30eedcff3bd725

###

#// insert kpi in spec
POST http://localhost:3000/spec/657046964a30eedcff3bd72e/kpis/65705174dc8928fb43ef9c9a